// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export const options = {
  vus : 10,
  duration : '30s',
}

export function handleSummary(data){
  return {
    "summary.html" : htmlReport(data)
  }
}

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    "reqres-url": "https://reqres.in"
  }
});

export default function() {
  postman[Request]({
    name: "LIST USER",
    id: "e0a04bfe-256a-4d34-a748-064a0ffa2821",
    method: "GET",
    address: "{{reqres-url}}/api/users?page=2"
  });

  postman[Request]({
    name: "SINGLE USER",
    id: "01b94b58-9382-47aa-bb5a-40a297f32ae4",
    method: "GET",
    address: "{{reqres-url}}/api/users/2"
  });

  // postman[Request]({
  //   name: "USER NOT FOUND",
  //   id: "4604e1c3-8c9b-4a33-8582-9ff0868684b0",
  //   method: "GET",
  //   address: "{{reqres-url}}/api/users/23"
  // });

  postman[Request]({
    name: "LIST RESOURCE",
    id: "37d1190f-71a4-4534-a04e-f217dc84ed49",
    method: "GET",
    address: "{{reqres-url}}/api/unknown"
  });

  postman[Request]({
    name: "SINGLE RESOURCE",
    id: "7caf8ca4-4538-490a-a261-8464aac7a731",
    method: "GET",
    address: "{{reqres-url}}/api/unknown/2"
  });

  // postman[Request]({
  //   name: "SINGLE RESOURCE NOT FOUND",
  //   id: "8314a332-2d6a-430f-823f-1bb3b91a1c14",
  //   method: "GET",
  //   address: "{{reqres-url}}/api/unknown/23"
  // });

  postman[Request]({
    name: "DELAYED RESPONSE",
    id: "475b0f1e-30ce-4284-86f2-7b5865ecee3d",
    method: "GET",
    address: "{{reqres-url}}/api/users?delay=3"
  });

  postman[Request]({
    name: "CREATE USER",
    id: "6a48643d-37ee-4b00-a9fc-fb8f5857c48a",
    method: "POST",
    address: "{{reqres-url}}/api/users",
    data: '{\n    "name": "morpheus",\n    "job": "leader"\n}'
  });

  postman[Request]({
    name: "REGISTER SUCCESSFUL",
    id: "244208cc-5e6a-4f01-a8d0-c9780a3f0693",
    method: "POST",
    address: "{{reqres-url}}/api/register",
    data: '{\n    "email": "eve.holt@reqres.in",\n    "password": "pistol"\n}'
  });

  // postman[Request]({
  //   name: "REGISTER UNSUCCESSFUL",
  //   id: "db6b2a1c-5c7f-49ed-a990-aaa8208e178a",
  //   method: "POST",
  //   address: "{{reqres-url}}/api/register",
  //   data: '{\n    "email": "eve.holt@reqres.in"\n}'
  // });

  postman[Request]({
    name: "LOGIN SUCCESSFUL",
    id: "56451eca-46ba-470a-aaee-e7d693b3ab40",
    method: "POST",
    address: "{{reqres-url}}/api/login",
    data: '{\n    "email": "eve.holt@reqres.in",\n    "password": "pistol"\n}'
  });

  // postman[Request]({
  //   name: "LOGIN UNSUCCESSFUL",
  //   id: "0d527a68-9a51-4b20-894d-7d28d10a48a5",
  //   method: "POST",
  //   address: "{{reqres-url}}/api/login",
  //   data: '{\n    "email": "eve.holt@reqres.in"\n}'
  // });

  postman[Request]({
    name: "UPDATE PUT",
    id: "0c9adc62-c3c7-42e5-ad90-c6f96f76b8e8",
    method: "PUT",
    address: "{{reqres-url}}/api/users/2",
    data: '{\n    "name": "morpheus",\n    "job": "zion resident"\n}'
  });

  postman[Request]({
    name: "UPDATE PATCH",
    id: "de674c33-a7d6-4db8-82ff-a0bc54c24763",
    method: "PATCH",
    address: "{{reqres-url}}/api/users/2",
    data: '{\n    "name": "morpheus",\n    "job": "zion resident"\n}'
  });

  postman[Request]({
    name: "DELETE USER",
    id: "53d0cf86-df59-43fb-ab23-75f6cf7ad23c",
    method: "DELETE",
    address: "{{reqres-url}}/api/users/2"
  });
}
